Add person student teacher class
Iptysam/School-library-OOP pull request #1
Opened 2023-04-12 10:47 UTC by Iptysam

Create class Person with the following:
Instance vars: @id, @name, and @age.
Constructor with name, age, and parent_permission as parameter. name and parent_permission are optional and have default values of "Unknown" and true.
Getters for @id, @name, and @age.
Setters for @name and @age.
Private method of_age? that returns true if @age is greater or equal to 18 and false otherwise.
Public method can_use_services? that returns true if person is of age or if they have permission from parents.
Create class Student with the following:
Inherits from Person.
Constructor extends parent's constructor by adding @classroom and a parameter for it.
Method play_hooky that returns "¯\(ツ)/¯".
Create class Teacher with the following:
Inherits from Person.
Constructor extends parent's constructor by adding @specialization and a parameter for it.
Override can_use_services? so it always returns true.
Each class should be saved in a separate file.

2023-04-12 10:53 UTC, Olamarx requested changes
Hi @Iptysam, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the readme set up professionally, kindly fix the comments I made as regards it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 10:53 UTC, Olamarx commented on README.md
> +- **[student.rb](student.rb)**
- [ ] Key feature means what are the key features of your app, not asking for link to the files, kindly add features, not links.

2023-04-12 10:53 UTC, Olamarx commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Kindly remove this dummy data

2023-04-12 10:53 UTC, Olamarx commented on README.md
> +Install this project with:
- [ ] With what? You must have missed that.

2023-04-12 18:43 UTC, rloterh reviewed
Hi Ipty, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly ensure to remove the Microverse template logo link in your ReadMe, which appears broken. Optionally, you can replace it with your own logo if you have one.

- [NOT A REASON FOR INVALIDATION] Also, I noticed you have double _Person_ class, and no _Student_ class. I urge you to refactor your code so as to ensure the appropriate classes are in place 😃 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-13 14:47 UTC, frank1738 approved these changes
Hi @Iptysam , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>

## Highlights
✅ Correct use of Github workflow
✅ No linter error
✅ Organized code

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 15:43 UTC, merged